language: python
python:
  - '3.7'

dist: bionic

# safelist
branches:
  only:
    - master

install: pip install -r requirements.txt

before_script:
  - pip install git+https://github.com/openfoodfacts/openfoodfacts-python

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=nutella.travis

script:
  - ./manage.py test

