# Generated by Django 2.2.4 on 2019-09-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='nutrition_grades',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd'), ('e', 'e')], help_text='The nutrition grade of article from openfoodfact api.', max_length=1),
        ),
    ]
