# Generated by Django 2.2.4 on 2019-09-10 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0002_auto_20190905_0517'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Substitute',
            new_name='ProfileSubstitute',
        ),
    ]
